version: '3.4'

services:
  films.application:
    image: ${DOCKER_REGISTRY-}filmsapplication
    build:
      context: .
      dockerfile: src/Services/Films/Films.WebApi/Dockerfile

  identity.application:
    image: ${DOCKER_REGISTRY-}identityapplication
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.WebApi/Dockerfile


  rating.application:
    image: ${DOCKER_REGISTRY-}ratingapplication
    build:
      context: .
      dockerfile: src/Services/Rating/Rating.WebApi/Dockerfile

